### ISSUE TITLE
Format Specification: Bad Link

### ISSUE THREAD

**Issue by MikeRatzlaff** [vividos/UnderworldAdventures#3]
In the format specification file, the link to this repository is shown as:
https://vividos.github.com/UnderworldAdventures

But that link doesn't work. It should be:
https://github.com/vividos/UnderworldAdventures

**Comment by vividos** [comment]
Thank you, I'll look at it!

**Comment by vividos** [comment]
btw, the correct link was: https://vividos.github.io/UnderworldAdventures/
