### ISSUE TITLE
Question about item combinations

### ISSUE THREAD

**Issue by KarlClinckspoor** [vividos/UnderworldAdventures#9]
Hey there, thanks for accepting my pull request. I didn't notice any other typos in the text.

I was messing around with CMB.DAT. I wanted to add other possible combinations for fun, but it seems anything past 10 entries is ignored, so I can add only 1 custom one. I tested it with GOG's version, with the mouselook patch. Do you know if/where that restriction is hardcoded in the engine? I can't for the life of me read assembly. If that's the case, do you think it would be a simple fix? If this enhancement could be added to a patcher, it would allow some cool stuff to be added into the game.

Thanks for your time,

**Comment by vividos** [comment]
Hi, sorry I don't know the answer either, but I can imagine that many things were hard coded into the executable back then...
